nelmio_api_doc:
    documentation:
        info:
            title: Leak Manager REST API
            description: REST API for Leak Web app and Leak Mobile App by Duffau Group
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc